    !-------------------------------------------------------------------------
    !-------------------------------------------------------------------------
    !
    ! ESTE CODIGO CREA LAS VARIABLES QUE SE UTILIZAN EN EL CODIGO
    !
    ! DATA:  15/09/2019
    ! AUTOR: Boris N. Rojo Tanzi
    !
    !--------------------------------------------------------------------------
    ! VARIABLES DE POSICION VELOCIDAD Y ACELERACION
    !--------------------------------------------------------------------------
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: U,V,W ! POSICION ACTUAL DT ANTERIOR Y POSTERIOR
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: DELTAPOS ! DELTA POSICION
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: U0,V0,W0 ! POSICION AL INICIO
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: VLX,VLY,VLZ ! VELOCIDAD
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: ACX,ACY,ACZ ! ACELERACION

    !--------------------------------------------------------------------------
    ! VARIABLES DE RESTRCCIONES Y CARGAS
    !--------------------------------------------------------------------------
    LOGICAL,ALLOCATABLE,DIMENSION(:,:) :: BDX,BDY,BDZ ! CONDICION DE BORDE
    LOGICAL :: BDSYM(3),BDASYM(3) ! CONDICION DE BORDE SYM/ASYM ENTRE CARAS
    LOGICAL,ALLOCATABLE,DIMENSION(:,:) :: LOX,LOY,LOZ ! CARGAS

    !--------------------------------------------------------------------------
    ! VARIABLES DE MASAS NODALES
    !--------------------------------------------------------------------------
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: MAS ! MASA EN EL NODO I
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: ROHN ! DENSIDAD NODAL

    !--------------------------------------------------------------------------
    ! VARIABLES DEL MATERIAL
    !--------------------------------------------------------------------------
    DOUBLE PRECISION DMP1,DMP2,DF ! COEFICIENTES DE AMORTIGUAMIENTO
    DOUBLE PRECISION CAF

    !--------------------------------------------------------------------------
    ! VARIABLES DE CONECTIVIDAD
    !--------------------------------------------------------------------------
    INTEGER,ALLOCATABLE,DIMENSION(:,:) :: CN ! CONECTIVIDAD DE LAS BARRAS
    INTEGER,DIMENSION(7) :: ELEMTYPE

    !--------------------------------------------------------------------------
    ! VARIABLES DE GEOMETRIA
    !--------------------------------------------------------------------------
    INTEGER M1,N1,L1 ! CANTIDAD DE CELDAS -1
    INTEGER M2,N2,L2 ! CANTIDAD DE CELDAS -2
    INTEGER MNL,NNT,NBT ! CANTIDAD DE CELDAS, NODOS Y BARRAS TOTALES
    INTEGER NNA,NBA ! CANTIDAD DE NODOS Y BARRAS A PARTIR DE LAS CONDICIONES DE SIMETRIA

    !--------------------------------------------------------------------------
    ! VARIABLES DE TIEMPO
    !--------------------------------------------------------------------------
    DOUBLE PRECISION TIME ! TIEMPO ACTUAL DE SIMULACION
    INTEGER STEP ! PASO DE TIEMPO
    INTEGER NSTEP ! NUMERO DE PASOS TOTALES
    INTEGER NDAMF ! NUMERO DE PASO PARA CAMBIO DE AMORTIGUAMIENTO
    INTEGER RUN ! NUMERO DE CORRIDA ACTUAL
    CHARACTER(LEN = 08) :: SDATEINFO ! YYYYMMDD INICIO
    CHARACTER(LEN = 10) :: STIMEINFO ! HHMMSS.SSS INICIO

    !--------------------------------------------------------------------------
    ! VARIABLES DE ENERGIA
    !--------------------------------------------------------------------------
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: DENCN ! DENSIDAD NODAL
    DOUBLE PRECISION ENEX               ! TRABAJO EXTERNO
    DOUBLE PRECISION ENIN               ! ENERGIA INTERNA TOTAL
    DOUBLE PRECISION ENCN, ENCNOLD      ! ENERGIA CINETICA
    DOUBLE PRECISION ENEL, ENELOLD      ! ENERGIA ELASTICA TOTAL
    DOUBLE PRECISION ENDP, ENDPOLD      ! ENERGIA DISIPADA POR AMORTECIMENTO
    DOUBLE PRECISION ENGD, ENGDOLD      ! ENERGIA DISIPADA (STRAIN SOFTENING)
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: ENGDB ! ENERGIA DISIPADA POR BARRA

    !--------------------------------------------------------------------------
    ! VARIABLES DE ALEATORIEDAD
    !--------------------------------------------------------------------------
    DOUBLE PRECISION,DIMENSION(16,16,16) :: PHI1,PHI2,PHI3,PHI4
    DOUBLE PRECISION,DIMENSION(16,16,16) :: AN
    DOUBLE PRECISION K1,K2,K3,DK1,DK2,DK3
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) ::  PHIGFR,PHIYNG,PHIROH
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) ::  PPGFR,PPYNG,PPROH
    DOUBLE PRECISION PHIV
    INTEGER NK1,NK2,NK3
    INTEGER,DIMENSION(4) :: NPTROH,NPTYNG,NPTGFR ! X,Y,Z,TOT

    !--------------------------------------------------------------------------
    ! VARIABLES DE ENTRADA SALIDA DE DATOS
    !--------------------------------------------------------------------------
    INTEGER PR03,PR04,PR05,PR06,PR07,PR08,PR09,PR10,PR11,PR12,PR13,PR14,PR16,PR17 ! CONTADOR PARA LAS SALIDA DE DATOS

    !--------------------------------------------------------------------------
    ! PROPIEDADES DE LAS BARRAS
    !--------------------------------------------------------------------------
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: LI ! LONGITUD INICIAL DE LA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: LBAR ! LONGITUD DE LA BARRA EN EL TIEMPO ACTUAL
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: XB0,YB0,ZB0 ! POSICION INICIAL DEL CENTRO DE LA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: XB,YB,ZB ! POSICION DEL CENTRO DE LA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: EP ! VALOR DE EP EN CADA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: EPMIN, EPMAX ! VALOR MIN MAX DE EP
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: KR ! RELACION EP ER
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: EM ! DEFORMACION MAXIMA EN CADA BARRA, A CADA INTERVALO
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: ER ! DEFORMACION MAXIMA EN CADA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: YNGB ! MODULO DE ELASTISIDAD DE CADA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: GFRB  ! ENERGIA ESPECIFICA DE CADA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: STR ! DEFORMACION DE LA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: STROLD ! DEFORMACION DE LA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: DSTR ! DERIVADA DEFORMACION DE LA BARRA
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: ECOMP ! PSEUDORIGIDEZ A COMPRESION
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: ETRAC ! PSEUDORIGIDEZ A TRACCION
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: ENR ! RIGIDEZ DE LAS BARRAS NORMALES
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: EDG ! RIGIDEZ DE LAS BARRAS DIAGONALES
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: LCR ! LONGITUD CRITICA DE LAS BARRAS
    LOGICAL,ALLOCATABLE,DIMENSION(:)   :: FS    ! ROTURRA DE LA BARRA
    LOGICAL,ALLOCATABLE,DIMENSION(:)   :: FSOLD ! ROTURRA DE LA BARRA
    LOGICAL,ALLOCATABLE,DIMENSION(:,:) :: DM    ! DANO EN LA BARRA
    LOGICAL,ALLOCATABLE,DIMENSION(:)   :: DMOLD ! DANO EN LA BARRA
    
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: FRX,FRY,FRZ ! FUERZA INTERNAS DEL MODELO
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: FORCE ! FUERZA EN CADA BARRA

    !--------------------------------------------------------------------------
    ! CONSTANTES
    !--------------------------------------------------------------------------
    DOUBLE PRECISION GMA,BTA ! ??? USADAS EN STATICS
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: MEAN ! LONG
    DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: COEV ! LONG
    INTEGER,ALLOCATABLE,DIMENSION(:) :: NODECTR ! NODOS DE CONTROL PARA SALIDA DE DATOS