    !-------------------------------------------------------------------------
    !-------------------------------------------------------------------------
    !
    MODULE VARIABLES_DATA
    IMPLICIT NONE
    !
    ! ESTE MODULO CREA LAS VARIABLES DE DATOS DE ENTRADA DEL PROGRAMA
    !
    ! DATA:  15/09/2019
    ! AUTOR: Boris N. Rojo Tanzi
    !
    !--------------------------------------------------------------------------   
    INTEGER TEST            ! TEST: NUMERO DE TEST
    INTEGER NRUN            ! NRUM: NUMERO DE CORRIDAS
    INTEGER SEED            ! SEED: NUMERO DE "SEMILLA"
    INTEGER LAW             ! LAW: NUMERO DE LEY CONSTITUTIVA

    DOUBLE PRECISION  LCO   ! LCO: TAMANO DE CELDA
    INTEGER M               ! M: CANTIDAD DE CELDAS EN X
    INTEGER N               ! N: CANTIDAD DE CELDAS EN Y
    INTEGER L               ! L: CANTIDAD DE CELDAS EN Z

    DOUBLE PRECISION PSN     ! PSN: POISSON
    DOUBLE PRECISION ROH     ! ROH: DENSIDAD
    DOUBLE PRECISION YNG     ! YNG: MODULO DE ELASTISIDAD
    DOUBLE PRECISION GFR     ! GFR: ENERGIA DE FRACTURA
    DOUBLE PRECISION RFC     ! RFC: FACTOR DE FALLA --OLD--
    DOUBLE PRECISION DEQ     ! DEQ: DIMENCION DE FALLA
    DOUBLE PRECISION REET    ! REET: RELACION EP'/EP PARA LEY TRILINEAL
    DOUBLE PRECISION REYNG   ! REYNG: RELACION ENTRE E'/E PARA LEY TRILINEAL
    DOUBLE PRECISION CORRCAF ! CORRCAF: FACTOR DE MULTIPLICACION DE CAF PARA COMPATIBILIZAR MALLA
    INTEGER EST              ! EST: TIPO DE AMORTIGUAMIENTO, 0: PATRON, 1: PATRON + PROPORCIONAL A RIGIDEZ, 2: PROPORCIONAL A LA MASA
    DOUBLE PRECISION DF1     ! DF1: COEFICIENTE DE AMORTIGUAMIENTO PARA EL PRIMER INTERVALO (0 A TDAF)
    DOUBLE PRECISION DF2     ! DF2: COEFICIENTE DE AMORTIGUAMIENTO PARA EL SEGUNDO INTERVALO (TDAF A TTOT)
    DOUBLE PRECISION TDAF    ! TDAF: TIEMPO EN EL QUE CAMBIA EL AMORTIGUAMIENTO DF1 A DF2
    DOUBLE PRECISION CON     ! CON: AMORTIGUAMIENTO DENTRO DE LA ECUACION CONSTITUTIVA (EST = 1)

    DOUBLE PRECISION CVUVW(3)  ! CVUVW: COEFICIENTE DE VARIACION PARA IMPERFECCION EN MALLA
    DOUBLE PRECISION BORDERUVW ! BORDERUVW: BORDE SIN IMPERFECCION
    
    DOUBLE PRECISION LCXROH    ! LCXROH: LONGITUD DE CORELACION PARA DENSIDAD
    DOUBLE PRECISION LCYROH    ! LCYROH: LONGITUD DE CORELACION PARA DENSIDAD
    DOUBLE PRECISION LCZROH    ! LCZROH: LONGITUD DE CORELACION PARA DENSIDAD
    DOUBLE PRECISION ROTROH(3) ! ROTROH: ANGULOS DE ROTACION EN EL CAMPO DE CORELACION PARA DENSIDAD
    DOUBLE PRECISION CVROH     ! CVROH: COEFICIENTE DE VARIACION PARA DENSIDAD
    DOUBLE PRECISION LCXYNG    ! LCXYNG: LONGITUD DE CORELACION PARA MODULO DE ELASTISIDAD
    DOUBLE PRECISION LCYYNG    ! LCYYNG: LONGITUD DE CORELACION PARA MODULO DE ELASTISIDAD
    DOUBLE PRECISION LCZYNG    ! LCZYNG: LONGITUD DE CORELACION PARA MODULO DE ELASTISIDAD
    DOUBLE PRECISION ROTYNG(3) ! ROTYNG: ANGULOS DE ROTACION EN EL CAMPO DE CORELACION PARA MODULO DE ELASTISIDAD
    DOUBLE PRECISION CVYNG     ! CVYNG: COEFICIENTE DE VARIACION PARA MODULO DE ELASTISIDAD
    DOUBLE PRECISION LCXGFR    ! LCXGFR: LONGITUD DE CORELACION PARA ENERGIA ESPECIFICA
    DOUBLE PRECISION LCYGFR    ! LCYGFR: LONGITUD DE CORELACION PARA ENERGIA ESPECIFICA
    DOUBLE PRECISION LCZGFR    ! LCZGFR: LONGITUD DE CORELACION PARA ENERGIA ESPECIFICA
    DOUBLE PRECISION ROTGFR(3) ! ROTYNG: ANGULOS DE ROTACION EN EL CAMPO DE CORELACION PARA ENERGIA ESPECIFICA
    DOUBLE PRECISION CVGFR     ! CVGFR: COEFICIENTE DE VARIACION PARA ENERGIA ESPECIFICA
    
    DOUBLE PRECISION DT      ! DT: INCREMENTO DE TIEMPO
    DOUBLE PRECISION TTOT    ! TTOT: TIEMPO TOTAL

    DOUBLE PRECISION AENCN     ! AENCN: AMPLITUD DE ENERGIA CINETICA EN CADA PASO
    INTEGER INCO  ! INCO: CANT. NODOS PARA SALIDA DE DATOS
    INTEGER,ALLOCATABLE,DIMENSION(:) :: NCON ! NCON: LECTURA DE NODOS
    INTEGER IBCO  ! INCO: CANT. NODOS PARA SALIDA DE DATOS
    INTEGER,ALLOCATABLE,DIMENSION(:) :: BCON ! NCON: LECTURA DE NODOS

    INTEGER OU02 ! CONTROL: CONTROL_OUT_TXX.DAT
    INTEGER OU03 ! ANSYS: ANSYS_TXX_pppppp.MAC
    INTEGER OU04 ! ANSYS: ANSYSFEM_TXX_pppppp.MAC
    INTEGER OU05 ! ACELERACION: ACELERATION_TXX.DAT
    INTEGER OU06 ! VELOCIDAD: VELOCITY_TXX.DAT
    INTEGER OU07 ! DESPLAZAMIENTO: POSITION_TXX.DAT
    INTEGER OU08 ! ENERGIA: ENERGY_TXX.DAT
    INTEGER OU09 ! BARRAS ROTAS: BARBROKEN_TXX.DAT
    INTEGER OU10 ! BARRAS DAÑADAS: BARDAMAGEN_TXX.DAT
    INTEGER OU11 ! TENSION DEFORMACION: STRESS_TXX.DAT
    INTEGER OU12 ! PARAVIEW: PARAVIEW_Txx_pppppp.vtk
    INTEGER OU13 ! MODELO DE BARRAS: MODEL_Txx_pppppp.dat
    INTEGER OU14 ! LEY CONTITUTIVA: CONSTIT_Txx_pppppp.dat
    INTEGER OU15 ! POLOS: POLOS_Type_Txx.dat
    INTEGER OU16 ! Delta Energia: DeltaENCN_Txx.dat
    INTEGER OU17 ! FORCE: FORCE_Txx.dat
    INTEGER OU18 ! DISPLECEMENT: BOUND_Txx.dat
    
    INCLUDE 'VARIABLES_DEM.f90'
    
    CONTAINS
    INCLUDE 'writefiles/CLEARFILE.f90'
    INCLUDE 'main/READAT.f90'
    INCLUDE 'main/PREPVAR.f90'
    INCLUDE 'main/COORD.f90'
    INCLUDE 'main/IMPERF.f90'
    INCLUDE 'main/edit_type_element.f90'
    INCLUDE 'subrutines/COORDSUB.f90'
    INCLUDE 'main/BOUND.f90'
    INCLUDE 'main/LOAD.f90'
    INCLUDE 'main/CREATENBSYM.f90'
    INCLUDE 'subrutines/RESIZESYM.f90'
    INCLUDE 'main/NODMASS.f90'
    INCLUDE 'randomness/INIROH.f90'
    INCLUDE 'function/RAN0.f90'
    INCLUDE 'function/RAND1.f90'
    INCLUDE 'function/ROTMAT.f90'
    INCLUDE 'main/CONECTI.f90'
    INCLUDE 'main/CALCTIME.f90'
    INCLUDE 'subrutines/EXTCO1.f90'
    INCLUDE 'subrutines/INTCO1.f90'
    INCLUDE 'subrutines/DIACO1.f90'
    INCLUDE 'main/CALAUX.f90'
    INCLUDE 'main/ALEATPYNG.f90'
    INCLUDE 'main/ALEATPGFR.f90'
    INCLUDE 'main/NAYFES8.f90'
    INCLUDE 'subrutines/UBARPOLO.f90'
    INCLUDE 'subrutines/INTPOLO.f90'
    INCLUDE 'subrutines/DEBBARRAS.f90'
    INCLUDE 'main/STATISTICS.f90'
    INCLUDE 'subrutines/FPROB.f90'
    INCLUDE 'main/RMEC.f90'
    INCLUDE 'subrutines/RMECEX.f90'
    INCLUDE 'subrutines/RMECIN.f90'
    INCLUDE 'subrutines/RMECDI.f90'
    INCLUDE 'subrutines/RANDMEC.f90'
    INCLUDE 'main/CALCOEV.f90'
    INCLUDE 'main/EDITGEOM.f90'
    INCLUDE 'writefiles/OPEN_FILES.f90'
    INCLUDE 'writefiles/OPEN_MODEL.f90'
    INCLUDE 'writefiles/ANSYS.f90'
    INCLUDE 'writefiles/MODEL.f90'
    INCLUDE 'writefiles/PARAVIEW.f90'
    INCLUDE 'writefiles/WRIBARDAMAGED.f90'
    INCLUDE 'writefiles/WRIBARBROKEN.f90'
    INCLUDE 'writefiles/WRIENCN.f90'
    INCLUDE 'main/CALOAD.f90'
    INCLUDE 'main/CABAR.f90'
    INCLUDE 'constits/CONSTIT_LIN.f90'
    INCLUDE 'constits/CONSTIT_BI.f90'
    INCLUDE 'constits/CONSTIT_BI_SHEAR.f90'
    INCLUDE 'constits/CONSTIT_TRI.f90'
    INCLUDE 'main/INTEGRATION.f90'
    INCLUDE 'subrutines/APPLYSYM.f90'
    INCLUDE 'main/ENERG.f90'
    INCLUDE 'writefiles/WRIENE.f90'
    INCLUDE 'writefiles/WRITEN.f90'
    INCLUDE 'writefiles/WRIPOS.f90'
    INCLUDE 'writefiles/WRIVEL.f90'
    INCLUDE 'writefiles/WRIACEL.f90'
    INCLUDE 'writefiles/WRICONTR.f90'
    INCLUDE 'writefiles/WRICONST.f90'
    INCLUDE 'writefiles/WRIPOLOS.f90'
    INCLUDE 'writefiles/WRIFORCE.f90'
    INCLUDE 'writefiles/WRIBOUND.f90'
    INCLUDE 'subrutines/DELAYTIME.f90'
    INCLUDE 'subrutines/PRISMEDITGEOM.f90'
    INCLUDE 'subrutines/ELEMENTFAMILY.f90'
    
    END MODULE VARIABLES_DATA
